import { Property } from '../../src/types';

export const MOCK_TEST_PROPERTIES: Property[] = [
  {
    id: 'prop-1',
    title: 'Luxury Beachfront Villa',
    description: 'Breathtaking sea view villa in North Coast with private pool and garden.',
    price: 15000000,
    location: 'North Coast, Egypt',
    bedrooms: 5,
    bathrooms: 4,
    area: 450,
    propertyType: 'Villa',
    compound: 'Marassi',
    developer: 'Emaar Misr',
    deliveryDate: 'Ready',
    finishing: 'Fully Finished',
    floor: 'Ground',
    view: 'Sea',
    furnished: true,
    contactPhone: '+201000000001',
    amenities: ['Swimming Pools', 'Clubhouse', 'Security', 'Landscape'],
    currency: 'EGP',
    status: 'For Sale',
    availability: 'Available',
    isVerified: true,
    verificationStatus: 'Verified',
    imageUrl: 'https://images.unsplash.com/photo-1580587771525-78b9dba3b914?auto=format&fit=crop&w=800&q=80',
    images: [
      'https://images.unsplash.com/photo-1580587771525-78b9dba3b914?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=800&q=80',
    ],
    panoramas: [
      'https://images.unsplash.com/photo-1580587771525-78b9dba3b914?auto=format&fit=crop&w=1200&q=80',
    ],
    digitalTwinUrl: 'https://my.matterport.com/show/?m=sample123',
    unitCode: 'HET-1001',
    registrationNumber: 'REG-987654',
    courtSignatureValidity: true,
    isResale: false,
    paymentMethods: ['Cash', 'Installments'],
    publishDate: '2026-02-01',
    yallaSahel: true,
    village: 'Marassi',
  },
  {
    id: 'prop-2',
    title: 'Modern New Cairo Penthouse',
    description: 'High-end rooftop penthouse in the Fifth Settlement with panoramic city views.',
    price: 8500000,
    location: 'New Cairo, Egypt',
    bedrooms: 3,
    bathrooms: 3,
    area: 280,
    propertyType: 'Penthouse',
    compound: 'Mivida',
    developer: 'Emaar Misr',
    deliveryDate: '2026-12-01',
    finishing: 'Semi Finished',
    floor: 'Roof',
    view: 'Open City View',
    furnished: false,
    contactPhone: '+201000000002',
    amenities: ['Gym', 'Underground Garage', 'Security'],
    currency: 'EGP',
    status: 'For Sale',
    availability: 'Available',
    isVerified: false,
    verificationStatus: 'Pending',
    imageUrl: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=800&q=80',
    images: [
      'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=800&q=80',
    ],
    unitCode: 'HET-1002',
    registrationNumber: 'REG-123456',
    courtSignatureValidity: true,
    isResale: true,
    paymentMethods: ['Cash', 'Bank Transfer'],
    publishDate: '2026-02-15',
    yallaSahel: false,
  },
  {
    id: 'prop-3',
    title: 'Cozy Chalet for Rent',
    description: 'Charming seaside rental unit near the crystal lagoon.',
    price: 3500,
    location: 'North Coast, Egypt',
    bedrooms: 2,
    bathrooms: 1,
    area: 110,
    propertyType: 'Chalet',
    compound: 'Hacienda Bay',
    developer: 'Palm Hills',
    deliveryDate: 'Ready',
    finishing: 'Fully Finished',
    floor: '1st Floor',
    view: 'Pool',
    furnished: true,
    contactPhone: '+201000000003',
    amenities: ['Lagoons', 'Swimming Pools', 'Kids Area'],
    currency: 'EGP',
    pricePeriod: 'night',
    status: 'For Rent',
    availability: 'Available',
    isVerified: true,
    verificationStatus: 'Verified',
    imageUrl: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=800&q=80',
    unitCode: 'HET-1003',
    publishDate: '2026-02-20',
    yallaSahel: true,
    village: 'Hacienda Bay',
    guests: 4,
  },
  {
    id: 'prop-4',
    title: 'Zayed Contemporary Townhouse',
    description: 'Family townhouse with private garden in Sheikh Zayed prime location.',
    price: 6200000,
    location: 'Sheikh Zayed, Egypt',
    bedrooms: 4,
    bathrooms: 3,
    area: 240,
    propertyType: 'Townhouse',
    compound: 'Allegria',
    developer: 'SODIC',
    deliveryDate: 'Ready',
    finishing: 'Finished',
    floor: '2 Floors',
    view: 'Golf Course',
    furnished: false,
    contactPhone: '+201000000004',
    amenities: ['Sports Fields', 'Jogging Track', 'Clubhouse'],
    currency: 'EGP',
    status: 'For Sale',
    availability: 'Reserved',
    isVerified: true,
    verificationStatus: 'Verified',
    imageUrl: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=800&q=80',
    unitCode: 'HET-1004',
    publishDate: '2026-01-10',
    yallaSahel: false,
  },
  {
    id: 'prop-5',
    title: 'Downtown Administrative Office',
    description: 'Modern office space suitable for consulting firms or tech startups.',
    price: 4500000,
    location: 'New Cairo, Egypt',
    bedrooms: 0,
    bathrooms: 2,
    area: 150,
    propertyType: 'Office',
    compound: 'Business Park',
    developer: 'Marakez',
    deliveryDate: 'Ready',
    finishing: 'Fully Finished',
    floor: '3rd Floor',
    view: 'Main Plaza',
    furnished: false,
    contactPhone: '+201000000005',
    amenities: ['Underground Garage', 'EV Chargers', '24/7 Security'],
    currency: 'EGP',
    status: 'For Sale',
    availability: 'Sold',
    isVerified: false,
    verificationStatus: 'Pending',
    imageUrl: 'https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=800&q=80',
    unitCode: 'HET-1005',
    publishDate: '2025-12-01',
    yallaSahel: false,
  }
];
